### ISSUE TITLE
Package for Raspbian

### ISSUE THREAD

**Issue by kvvloten** [miterion/ldap2carddav#1]
I would love to run ldap2carddav on Raspbian. 
Would it be possible to create a deb-package for it?

**Comment by miterion** [comment]
I updated the goreleaser config and since some version there are also automatic ARM builds. There is a [new release](https://github.com/miterion/ldap2carddav/releases/tag/v0.2.6), would be nice if you could test this and give me feedback.

**Comment by kvvloten** [comment]
It looks like Raspbian is not able to run arm64:

root@myhost:~# ldap2carddav
-bash: /usr/local/sbin/ldap2carddav: cannot execute binary file: Exec format error

Can you compile a 32-bits binary?

**Comment by miterion** [comment]
Sure, take a look at the latest release [0.2.8](https://github.com/miterion/ldap2carddav/releases/tag/v0.2.8)

**Comment by kvvloten** [comment]
Much better, it works now :-)

**Comment by miterion** [comment]
Great, closing this issue
