### ISSUE TITLE
Anonymous bind not supported?

### ISSUE THREAD

**Issue by kvvloten** [miterion/ldap2carddav#2]
When bindpw in /etc/ldap2carddav is not specified or empty string ldap2carddav fails with:

Error binding to LDAP: LDAP Result Code 206 "Empty password not allowed by the client": ldap: empty password not allowed by the client 

Is there another way to allow anonymous bind to ldap or is it currently not supported?

**Comment by miterion** [comment]
I implemented this in 59f2d25 on the anonymous-bind branch. Can you try it again with that commit applied (if you want I can compile it for you if you name the platform)?

**Comment by kvvloten** [comment]
Thanks, that is a quick response.
Can you build an amd64 binary?

**Comment by miterion** [comment]
Sure, here you go [ldap2carddav_v0.2.6-next_Linux_x86_64.tar.gz](https://github.com/miterion/ldap2carddav/files/6771821/ldap2carddav_v0.2.6-next_Linux_x86_64.tar.gz)

**Comment by kvvloten** [comment]
It works, this is indeed the expected output:

[LDAPWorker] 2021/07/06 20:18:26 Starting scrape
[LDAPWorker] 2021/07/06 20:18:26 LDAP Password empty, using unauthenticated bind.
[LDAPWorker] 2021/07/06 20:18:26 Found 6 users

Tnx !

**Comment by miterion** [comment]
Cool, will be in the next release.
