### ISSUE TITLE
Limit listener to a single IP

### ISSUE THREAD

**Issue by kvvloten** [miterion/ldap2carddav#3]
Currently the listener always listens to 0.0.0.0 with a port from the config-file. 
I would like to put it behind an Apache reversed proxy, i.e.in my case it would listen to 127.0.0.1:8000. 
Would it be possible the make the listener-IP a config parameter?

**Comment by miterion** [comment]
I implemented this in 59f53a93442c35b4fed4a02e72ab8fca02b185b1. Will be in the 0.2.7 release.
