### ISSUE TITLE
Question: how to check service output?

### ISSUE THREAD

**Issue by kvvloten** [miterion/ldap2carddav#4]
As such ldap2carddav runs properly now:

Jul 07 19:22:40 myhost systemd[1]: Started Ldap2carddav Server.
Jul 07 19:22:40 myhost ldap2carddav[24714]: 2021/07/07 19:22:40 Starting carddav server on 127.0.0.1:8000
Jul 07 19:22:40 myhost ldap2carddav[24714]: [LDAPWorker] 2021/07/07 19:22:40 Starting scrape
Jul 07 19:22:40 myhost ldap2carddav[24714]: [LDAPWorker] 2021/07/07 19:22:40 LDAP Password empty, using unauthenticated bin
Jul 07 19:22:40 myhost ldap2carddav[24714]: [LDAPWorker] 2021/07/07 19:22:40 Found 6 users

However I have not found out how to get data out of it. 
I have tried to connect with the cardbook addon in Thunderbird but that fails in the "validation" step of setting up carddav client. Then I tried with curl but it looks like every attempt fails with:

400 Bad Request: EOF

My config is:
---
ldap:
  url: "ldaps://server.example.com/"
  basedn: "OU=Users,DC=example,DC=com"
  filter: "(objectClass=user)"
  scrapetime: "6000s"

carddav:
  storagepath: "addressbook"
  subdirectory: "/"
  address: "127.0.0.1"
  port: 8000

Is it possible to enable more verbose logging?
What curl call should show some output?

**Comment by miterion** [comment]
I used this curl command during debugging sessions:
`curl  --request PROPFIND --header "Content-Type: text/xml" --data "<?xml version=\"1.0\" encoding=\"utf-8\"?><D:propfind xmlns:D=\"DAV:\" xmlns:C=\"urn:ietf:params:xml:ns:carddav\"><D:prop><C:addressbook-home-set/></D:prop></D:propfind>" <url> | xmllint -format -`

If you see a long XML document with entries such as
```
  <response xmlns="DAV:">
    <href>contact.vcf</href>
    <propstat xmlns="DAV:">
      <prop xmlns="DAV:">
        <addressbook-home-set xmlns="urn:ietf:params:xml:ns:carddav"/>
      </prop>
      <status>HTTP/1.1 404 Not Found</status>
    </propstat>
    <status>HTTP/1.1 200 OK</status>
  </response>
```
it works in principle.

You can also debug it in cardbook by using the LogViewer under the tools section.

Regarding your config: Are you maybe hosting the carddav server under a subdirectory (e.g. `https://example.com/carddav`)? In that case you have to set the subdirectory setting in the config to this value (in the example it would have to be set to `/carddav/`).

**Comment by kvvloten** [comment]
Thanks, that is a good start !
I have moved it behind the reverse proxy under `/davldap` and set the subdirectory accordingly.

``` 
curl -u user:password -s --request PROPFIND --header "Content-Type: text/xml" --data "<?xml version=\"1.0\" encoding=\"utf-8\"?><D:propfind xmlns:D=\"DAV:\" xmlns:C=\"urn:ietf:params:xml:ns:carddav\"><D:prop><C:addressbook-home-set/></D:prop></D:propfind>" https://server.example.com/davldap | xmllint -

<?xml version="1.0" encoding="UTF-8"?>
<multistatus xmlns="DAV:">
  <response xmlns="DAV:">
    <href>/davldap</href>
    <propstat xmlns="DAV:">
    <prop xmlns="DAV:">
    <addressbook-home-set xmlns="urn:ietf:params:xml:ns:carddav"> <href xmlns="DAV:">/davldap</href>
    </addressbook-home-set>
    </prop><status>HTTP/1.1 200 OK</status></propstat>
    <status>HTTP/1.1 200 OK</status>
  </response>
</multistatus>
```
So far, so good.
When I add the a calendar in Thunderbird Cardbook, it validates correctly and it creates an addressbook with the name `LDAP Adressbook`. And that is all it does, it does not return the 6 users I was expecting to see:

```
2021/07/08 19:23:55 Starting carddav server on 127.0.0.1:8000
[LDAPWorker] 2021/07/08 19:23:55 Starting scrape
[LDAPWorker] 2021/07/08 19:23:55 LDAP Password empty, using unauthenticated bind.
[LDAPWorker] 2021/07/08 19:23:55 Found 6 users
```
The daemon (which runs on the console) does not show more output then the above 4 lines and the `Log viewer` in Cardbook remains empty even when I click `synchronize`. 
The LDAP backend is Samba4 (4.14), with config applied to allow anonymous access to the users. Other tools like the Apache reverse proxy sitting in front of ldap2carddav also use this to check the user/group (that is why I run curl with `-u user:password`)

Do you have any clue what goes wrong here?

**Comment by miterion** [comment]
It looks like the general setup is working but you are hosting the application under a subdirectory `/davldap`. Can you set `subdirectory:  /davldap/` in the ldap2carddav.yml, restart the application and try again?

**Comment by kvvloten** [comment]
Tried the / at the end, no change.
I have taken a shortcut and eliminated the apache2 reverse proxy for now:
```
---
ldap:
  url: "ldaps://ldapserver.example.com"
  basedn: "OU=User Accounts,OU=Client Users,OU=Users,DC=example,DC=com"
  filter: "(objectClass=user)"
  scrapetime: "6000s"

carddav:
  storagepath: "addressbook"
  subdirectory: "/"
  port: 8000
```
I have connected Cardbook directly to the ldap2carddav, which I have started from the prompt in order to see all its output (which still states: `Found 6 users`)
Output in the Cardbook's Log Viewer:
```
2021.07.09 13:07:01:728 : LDAP Adressbook : Discovering phase 1 request on http://server.example.com:8000/.well-known/carddav …
2021.07.09 13:07:01:749 : LDAP Adressbook : Discovering phase 2 request on http://server.example.com:8000/ …
2021.07.09 13:07:01:762 : LDAP Adressbook : Discovering phase 3 request on http://server.example.com:8000/ …
2021.07.09 13:07:01:776 : LDAP Adressbook : Searching contacts …
2021.07.09 13:07:02:791 : LDAP Adressbook : Synchronization finished, contacts result :
2021.07.09 13:07:02:791 : LDAP Adressbook : Contacts up to date : 0
2021.07.09 13:07:02:791 : LDAP Adressbook : Contacts new on server : 0
2021.07.09 13:07:02:791 : LDAP Adressbook : Contacts updated on server : 0
2021.07.09 13:07:02:791 : LDAP Adressbook : Contacts deleted from server : 0
2021.07.09 13:07:02:791 : LDAP Adressbook : Contacts deleted locally : 0
2021.07.09 13:07:02:791 : LDAP Adressbook : Contacts deleted locally and updated on server : 0
2021.07.09 13:07:02:791 : LDAP Adressbook : Contacts new locally : 0
2021.07.09 13:07:02:791 : LDAP Adressbook : Contacts updated locally : 0
2021.07.09 13:07:02:791 : LDAP Adressbook : Contacts updated locally and on server : 0
2021.07.09 13:07:02:791 : LDAP Adressbook : Contacts updated locally and deleted from server : 0
2021.07.09 13:07:02:791 : LDAP Adressbook : Modifications retrieved successfully from server : 0
2021.07.09 13:07:02:791 : LDAP Adressbook : Modifications retrieved unsuccessfully from server : 0
2021.07.09 13:07:02:791 : LDAP Adressbook : Modifications pushed successfully to the server : 0
2021.07.09 13:07:02:791 : LDAP Adressbook : Modifications pushed unsuccessfully to the server : 0
2021.07.09 13:07:02:791 : LDAP Adressbook : Images downloaded : 0
2021.07.09 13:07:02:792 : LDAP Adressbook : Images in error : 0
2021.07.09 13:07:02:792 : All synchronizations finished
```

I am wondering whether this is (sort of) the same issue as I had with Python-ldap and AD / Samba4. I had to turn off referrals in the ldap query to make it work. On the other hand with referrals ON it returned an error in Python and that seems to be different here. Link to the issue I faced: https://github.com/python-ldap/python-ldap/issues/275#issuecomment-635813344

**Comment by miterion** [comment]
If you want to check whether the LDAP sync worked you can look at the folder indicated by `storagepath` (which btw should be a full path such as `/srv/ldapcarddav`). If that folder contains some `*.vcf` files the initial sync is working

**Comment by kvvloten** [comment]
Good point about the `storagepath`, it was not a fullpath (as shown above), the relative path was taken from the `ldap2carddav.example.yml`. Perhaps it is a good idea to add a small readme to prevent these kinds of user errors :-)

Together with adding the `/` at the end of the `subdirectory` key, it fixed the issue!
I actually see the 6 users in Cardbook now. 
Thank you very much for your all your help!

One last request would be to make the addressbook name `LDAP Adressbook` a variable in the config file, so that I can choose the name of the addressbook as it is displayed in Cardbook.

**Comment by miterion** [comment]
Done in v0.2.9

**Comment by kvvloten** [comment]
Thanks that works!

Unfortunately I have just discovered a sync issue: I get an extra empty card in Cardbook.
Ldap2carddav is updated to 0.2.9 and started from the console, it outputs:
```
2021/07/11 12:26:51 Starting carddav server on 127.0.0.1:8000
[LDAPWorker] 2021/07/11 12:26:51 Starting scrape
[LDAPWorker] 2021/07/11 12:26:51 LDAP Password empty, using unauthenticated bind.
[LDAPWorker] 2021/07/11 12:26:51 Found 4 users
```
This is similar to what I see on the server's filesystem:
```
ls -l 
total 16
-rw-r--r-- 1 ldap2carddav ldap2carddav 174 Jul 11 12:18 kvv.vcf
-rw-r--r-- 1 ldap2carddav ldap2carddav 162 Jul 11 12:18 test1.vcf
-rw-r--r-- 1 ldap2carddav ldap2carddav 162 Jul 11 12:18 test2.vcf
-rw-r--r-- 1 ldap2carddav ldap2carddav 168 Jul 11 12:18 test3.vcf
```
The I removed and re-created the addressbook in Cardbook. The list of cards show the 4 items + 1 empty item, Log viewer confirms that:
```
2021.07.11 12:25:46:717 : Composers adressen : Searching contacts …
2021.07.11 12:25:46:729 : Composers adressen : Address book created
2021.07.11 12:25:47:051 : Composers adressen : Found a new contact on server
2021.07.11 12:25:47:051 : Composers adressen : Found a new contact on server
2021.07.11 12:25:47:052 : Composers adressen : Found a new contact on server
2021.07.11 12:25:47:052 : Composers adressen : Found a new contact on server
2021.07.11 12:25:47:053 : Composers adressen : Found a new contact on server
2021.07.11 12:25:48:002 : Composers adressen : Contact  downloaded from server
2021.07.11 12:25:48:007 : Composers adressen : Contact Kees van Vloten downloaded from server
2021.07.11 12:25:48:011 : Composers adressen : Contact test 1 user downloaded from server
2021.07.11 12:25:48:014 : Composers adressen : Contact test 2 user downloaded from server
2021.07.11 12:25:48:017 : Composers adressen : Contact test user 3 downloaded from server
2021.07.11 12:25:48:752 : Composers adressen : Synchronization finished, contacts result :
2021.07.11 12:25:48:752 : Composers adressen : Contacts up to date : 0
2021.07.11 12:25:48:752 : Composers adressen : Contacts new on server : 5
2021.07.11 12:25:48:752 : Composers adressen : Contacts updated on server : 0
2021.07.11 12:25:48:752 : Composers adressen : Contacts deleted from server : 0
2021.07.11 12:25:48:752 : Composers adressen : Contacts deleted locally : 0
2021.07.11 12:25:48:752 : Composers adressen : Contacts deleted locally and updated on server : 0
2021.07.11 12:25:48:752 : Composers adressen : Contacts new locally : 0
2021.07.11 12:25:48:752 : Composers adressen : Contacts updated locally : 0
2021.07.11 12:25:48:753 : Composers adressen : Contacts updated locally and on server : 0
2021.07.11 12:25:48:753 : Composers adressen : Contacts updated locally and deleted from server : 0
2021.07.11 12:25:48:753 : Composers adressen : Modifications retrieved successfully from server : 5
2021.07.11 12:25:48:753 : Composers adressen : Modifications retrieved unsuccessfully from server : 0
2021.07.11 12:25:48:753 : Composers adressen : Modifications pushed successfully to the server : 0
2021.07.11 12:25:48:753 : Composers adressen : Modifications pushed unsuccessfully to the server : 0
2021.07.11 12:25:48:753 : Composers adressen : Images downloaded : 0
2021.07.11 12:25:48:753 : Composers adressen : Images in error : 0
2021.07.11 12:25:48:754 : All synchronizations finished
```
As you can see it finds 5 and syncs 5 cards, not 4. 
When I click on the 5th empty vcard in Cardbook, it shows all fields empty.
