### ISSUE TITLE
Vcards are not deleted when no longer in ldap-search output.

### ISSUE THREAD

**Issue by kvvloten** [miterion/ldap2carddav#6]
Vcards files on the filesystem are not removed when they are no longer in the output of the ldap-search.
Restart ldap2carddav to force a resync does not help.
BTW. does ldap2carddav do a periodic resync or does it require a restart to resync with ldap?

**Comment by miterion** [comment]
It automatically resyncs according to the time set in the scrape time setting

**Comment by miterion** [comment]
Deletion is possible since ca7173f
