### ISSUE TITLE
ldap objects without UID

### ISSUE THREAD

**Issue by ticktostick** [miterion/ldap2carddav#7]
Is there any way to sync LDAP objects without UID attribute the vcf file cannot be created for this objects and there is only one vcf without name ".vcf"  in storagepath
like a uid to other attribute mapper in config

And how to add more fields for other attributes in LDAP such as Home phone or IP phone

**Comment by miterion** [comment]
> Is there any way to sync LDAP objects without UID attribute the vcf file cannot be created for this objects and there is only one vcf without name ".vcf" in storagepath
like a uid to other attribute mapper in config

I guess the UID field could be made configurable as long as there is something else uniquely tied to each user in the LDAP.

> And how to add more fields for other attributes in LDAP such as Home phone or IP phone

I only did the mapping for a small amount of attributes and it is kind of all over the code. But it would be possible to refactor this into some sort of lookup table.

Feel free to send in a PR for these features.

**Comment by ticktostick** [comment]
sAMAccountName is in every LDAP user and its unique

**Comment by miterion** [comment]
I think adding it as an optional setting should work since this attribute is usually only available in Active Directory environments

**Comment by miterion** [comment]
Fixed in later versions. Unique attribute field is now configurable
